- name: Get public IP info
  azure.azcollection.azure_rm_publicipaddress_info:
    resource_group: rgUbuntuSoutheastAsia
    name: pipDockerDemo01
    auth_source: env
  register: ip_info

- name: Debug IP info
  debug:
    var: ip_info

- name: Save IP to file
  copy:
    content: "{{ ip_info.azure_publicipaddresses[0].ip_address | default('') }}"
    dest: vm_ip.txt
