- name: Get Public IP of VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get public IP info
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: rgUbuntuSoutheastAsia
        name: pipDockerDemo01
        auth_source: env
      register: ip_info

    - name: Debug IP info
      debug:
        var: ip_info

    - name: Fail if no public IP found
      fail:
        msg: "❌ ไม่พบ IP จาก Azure หรือข้อมูลว่าง"
      when: ip_info.publicipaddresses is not defined or ip_info.publicipaddresses | length == 0

    - name: Save IP to file (เขียนไว้ใน Jenkins workspace โดยตรง)
      copy:
        content: "{{ ip_info.publicipaddresses[0].ip_address }}"
        dest: "{{ lookup('env', 'WORKSPACE') | default('./') }}/vm_ip.txt"
