- name: "Open HTTP Port 80 on existing NSG"
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  tasks:
    - name: "Allow HTTP (port 80)"
      azure.azcollection.azure_rm_securityrule:
        name: AllowHTTP
        resource_group: rgUbuntuSoutheastAsia
        security_group_name: nicDockerDemo01
        access: Allow
        direction: Inbound
        protocol: Tcp
        priority: 1001
        source_address_prefix: "*"
        source_port_range: "*"
        destination_address_prefix: "*"
        destination_port_range: "80"
        state: present
