- name: Create NSG with allow port 80
  azure.azcollection.azure_rm_securitygroup:
    name: nsgDockerDemo01
    resource_group: rgUbuntuSoutheastAsia
    location: southeastasia
    security_rules:
      - name: AllowHTTP
        access: Allow
        direction: Inbound
        priority: 1001
        protocol: Tcp
        source_address_prefix: '*'
        source_port_range: '*'
        destination_address_prefix: '*'
        destination_port_range: '80'
    state: present
