# playbooks/open-port-80.yaml
- name: "Open port 80 on existing NSG"
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  tasks:
    - name: "Allow HTTP (port 80)"
      azure_rm_securityrule:
        name: AllowHTTP
        resource_group: rgUbuntuSoutheastAsia
        security_group_name: nsgDockerDemo01   # 👈 ระบุ NSG ที่ผูกอยู่กับ NIC แล้ว
        access: Allow
        direction: Inbound
        protocol: Tcp
        priority: 1001
        source_address_prefix: "*"
        source_port_range: "*"
        destination_address_prefix: "*"
        destination_port_range: "80"
